# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build:
    working_directory: ~/SPRINT4/se-git-demo/src
    docker:
      - image: cimg/node:lts
    steps:
      - checkout:
          path: ~/SPRINT4/se-git-demo
      - setup_remote_docker
      - run: npm install
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/SPRINT4/se-git-demo/src/caches
            docker save -o ~/SPRINT4/se-git-demo/src/caches/app.tar app
      - run: npm install
      - store_test_results:
          path: test-results
      #- run: npm test
