version: "3.8"

services:
  database:
    image: mysql
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
    ports:
      - 3306:3306

  webserver:
    build: ./src
    depends_on:
      - database
    restart: on-failure
    environment:
      - DATABASE_HOST=database
    ports:
      - 3000:3000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "8081:80"
